export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_ALL_POSTS = "GET_ALL_POSTS";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS";
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL";
export const GET_ALL_POSTS_FAIL = "GET_ALL_POSTS_FAIL";
